13 netsrv package
Serg3/go_course_thinknetika pull request #13
Opened 2021-06-24 10:01 UTC by Serg3

Part 13: Сетевое программирование (Network programming)

2021-06-26 15:22 UTC, DmitriyVTitov requested changes
Логика работы программы запутанна, подключаемый пакет некорректен.

2021-06-26 15:22 UTC, DmitriyVTitov commented on 13_search_engine/pkg/netsrv/netsrv.go
> +}
не понимаю смысла в этой функции

2021-06-26 15:22 UTC, DmitriyVTitov commented on 13_search_engine/cmd/srch/srch.go
> +	netsrv.Searcher(l, sp)
Я не понимаю что тут происходит. Конструктор вызывается после чего-то ещё. Имена крайне странные: почему-то объекты, выполняющие действия. Такие формы имён я не встречал.

2021-06-26 15:22 UTC, DmitriyVTitov commented on 13_search_engine/pkg/netsrv/netsrv.go
> +			log.Fatal(err)
Подключаемый пакет завершает программу аварийно. Вы уверены, что я именно этого жду от пакета? Я - нет.

2021-06-26 18:14 UTC, Serg3 commented on 13_search_engine/pkg/netsrv/netsrv.go
> +}
Не понял это условие задачи: "Служба “netsrv” должна принимать соединения на порту 8000 на всех сетевых интерфейсах системы.". То есть тогда перед listenet.Accept() сделать проверку на порт :8080 нужно? Если другой порт - возврат?

2021-06-26 18:24 UTC, Serg3 commented on 13_search_engine/cmd/srch/srch.go
> +	netsrv.Searcher(l, sp)
Вынесу весь запуск в инициализацию.

2021-06-26 18:25 UTC, Serg3 commented on 13_search_engine/pkg/netsrv/netsrv.go
> +			log.Fatal(err)
Переделаю.

2021-06-26 19:19 UTC, DmitriyVTitov commented on 13_search_engine/pkg/netsrv/netsrv.go
> +}
Порт указывается явно, литералом или константой, там нечего проверять.
Эта функция бессмысленна. Она вообще ничего не добавляет к `net.Listen`.  Зачем вообще такую функцию вводить?

2021-06-28 14:30 UTC, DmitriyVTitov requested changes
Не понимаю логику программы.

2021-06-28 14:30 UTC, DmitriyVTitov commented on 13_search_engine/cmd/srch/srch.go
> +	// errors handler from net service
какой ещё обработчик, не понял комментария

2021-06-28 14:30 UTC, DmitriyVTitov commented on 13_search_engine/cmd/srch/srch.go
> +	// errors handler from net service
комментарии нужны там, где нужны )

2021-06-28 14:30 UTC, DmitriyVTitov commented on 13_search_engine/pkg/netsrv/netsrv.go
> +}
какое всё это имеет отношение к обработке сетевых подключений?

2021-06-28 14:30 UTC, DmitriyVTitov commented on 13_search_engine/pkg/netsrv/netsrv.go
> +func ListenAndSearch(urls []string, depth int) error {
почему сетевая служба принимает какие-то URL и глубину? какое всё это имеет отношение к прослушиванию запросов?

2021-06-28 20:21 UTC, Serg3 commented on 13_search_engine/cmd/srch/srch.go
> +	// errors handler from net service
Это на тот случай, если был бы вопрос, а что дальше с этой ошибкой :)

2021-06-28 20:22 UTC, Serg3 commented on 13_search_engine/pkg/netsrv/netsrv.go
> +}
Согласен, задача вызывающего кода.

2021-06-28 20:22 UTC, Serg3 commented on 13_search_engine/pkg/netsrv/netsrv.go
> +func ListenAndSearch(urls []string, depth int) error {
Согласен, задача вызывающего кода.

2021-06-28 20:22 UTC, DmitriyVTitov commented on 13_search_engine/pkg/netsrv/netsrv.go
> +}
нет, это задача другого пакета

2021-06-30 16:26 UTC, DmitriyVTitov approved these changes
OK

2021-06-30 16:26 UTC, DmitriyVTitov commented on 13_search_engine/cmd/srch/srch.go
> +		go netsrv.Searcher(conn, docs)
Странные имена всё время. Почему Searcher? Имя функции - глагол или существительное. И вообще, тут обработчик.

2021-06-30 16:26 UTC, DmitriyVTitov commented on 13_search_engine/cmd/srch/srch.go
> +			continue
ОК

2021-06-30 17:39 UTC, merged