14 web application
Serg3/go_course_thinknetika pull request #14
Opened 2021-06-25 19:30 UTC by Serg3

Part 14: Веб-приложение (Web-application)

2021-06-28 14:27 UTC, DmitriyVTitov requested changes
Задача простая: запустить веб-приложение с двумя конечными точками. Программа должна при этом быть понятна.

2021-06-28 14:27 UTC, DmitriyVTitov commented on 14_search_engine/cmd/srch/srch.go
> +	webapp.ListenAndServe()
Функция, которая ничего не принимает и ничего не возвращает, не понятна совершенно. Вот что она делает? Как мне ей пользоваться?

2021-06-28 14:27 UTC, DmitriyVTitov commented on 14_search_engine/cmd/srch/srch.go
> +	webapp.PerformScan([]string{"https://golang.org", "https://go.dev"}, 2)
Скан куда? Куда и что сканируется? Вообще загадка. Почему функция не возвращает результаты сканирования?

2021-06-28 14:27 UTC, DmitriyVTitov commented on 14_search_engine/pkg/webapp/webapp.go
> +	http.ListenAndServe(":8080", r)
а если я захочу на другом порту запустить службу? как это сделать?

2021-06-28 14:27 UTC, DmitriyVTitov commented on 14_search_engine/pkg/webapp/webapp.go
> +	go docs(sp)
какой-то отдельный поток, пока что не понимаю логики

2021-06-28 14:27 UTC, DmitriyVTitov commented on 14_search_engine/pkg/webapp/webapp.go
> +var crwDocs []crawler.Document
а, вот оно что - всё хранится в глобальной переменной! это вообще не приветствуется (глобальные переменные), кроме того, это супер неочевидный вариант

2021-07-02 23:10 UTC, DmitriyVTitov requested changes

2021-07-02 23:10 UTC, DmitriyVTitov commented on 14_search_engine/cmd/srch/srch.go
> +	}
Опять вы что-то придумываете. Какие-то два булевых флажка, совершенно непонятных и точно лишних.

2021-07-02 23:10 UTC, DmitriyVTitov commented on 14_search_engine/cmd/srch/srch.go
> +	}
И никак не вяжется с именем переменной.

2021-07-02 23:10 UTC, DmitriyVTitov commented on 14_search_engine/pkg/webapp/webapp.go
> +	}
Ах вон оно что! Явно лишний артефакт.

2021-07-02 23:10 UTC, DmitriyVTitov commented on 14_search_engine/pkg/webapp/webapp.go
> +}
Почему один обработчик если две конечных точки? У каждого метода API должен быть свой!

2021-07-05 10:38 UTC, DmitriyVTitov requested changes
Одна функция - один тест.

2021-07-05 10:38 UTC, DmitriyVTitov commented on 14_search_engine/pkg/webapp/webapp.go
> +	}).Methods(http.MethodGet)
если нужно хранить состояние (docs), то лучше создать структуру с этим полем и определить обработчики как методы этой структуры (см. GoSearch)

2021-07-05 10:38 UTC, DmitriyVTitov commented on 14_search_engine/pkg/webapp/webapp_test.go
> +	}
какую функцию тестирует этот тест?
не понятно

2021-07-06 07:31 UTC, DmitriyVTitov requested changes

2021-07-06 07:31 UTC, DmitriyVTitov commented on 14_search_engine/cmd/srch/srch_test.go
> +	r := mux.NewRouter()
вот тут маршрутизатор пересоздаётся и при завершении функции все регистрации конечных точек потеряны

2021-07-08 09:45 UTC, DmitriyVTitov approved these changes
ОК

2021-07-08 09:45 UTC, DmitriyVTitov commented on 14_search_engine/cmd/srch/srch.go
> +}
обработчики лучше вынести в отдельный пакет

2021-07-08 09:45 UTC, DmitriyVTitov commented on 14_search_engine/cmd/srch/srch_test.go
> +func Test_crwDocs_docsHandler(t *testing.T) {
используйте IDE для генерации тестов, имена должны быть стандартные

2021-07-08 09:45 UTC, DmitriyVTitov commented on 14_search_engine/cmd/srch/srch_test.go
> +	}
зачем две одинаковых переменных?

2021-07-08 09:45 UTC, DmitriyVTitov commented on 14_search_engine/cmd/srch/srch_test.go
> +	get := string(body)
got

2021-07-08 11:59 UTC, Serg3 commented on 14_search_engine/cmd/srch/srch_test.go
> +func Test_crwDocs_docsHandler(t *testing.T) {
Это стандартный генератор VS Code так сделал.

2021-07-08 12:03 UTC, Serg3 commented on 14_search_engine/cmd/srch/srch.go
> +}
Принял.

2021-07-08 12:03 UTC, merged

2021-07-08 12:05 UTC, DmitriyVTitov commented on 14_search_engine/cmd/srch/srch_test.go
> +func Test_crwDocs_docsHandler(t *testing.T) {
ОК